import{a as w,S,i as l}from"./assets/vendor-DvfmeZXB.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const B="https://pixabay.com/api/",E="53377193-0ff55e0243d64b70ef9ccd5fb";async function m(t,r){const n={key:E,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r};return(await w.get(B,{params:n})).data}const a={formEl:document.querySelector(".form"),galleryElement:document.querySelector(".gallery"),loaderBackdrop:document.querySelector(".loader-backdrop"),loadMoreBtn:document.querySelector(".load-more")},q=new S(".gallery a",{captionsData:"alt",captionDelay:250});function g(t){const r=t.map(({largeImageURL:n,webformatURL:i,tags:e,likes:o,views:s,comments:b,downloads:L})=>`
      <li class="gallery-item">
        <a href="${n}">
          <img src="${i}" alt="${e}">
        </a>
        <ul class="card-info">
          <li><b>Likes:</b> ${o}</li>
          <li><b>Views:</b> ${s}</li>
          <li><b>Comments:</b> ${b}</li>
          <li><b>Downloads:</b> ${L}</li>
        </ul>
      </li>
    `).join("");a.galleryElement.insertAdjacentHTML("beforeend",r),q.refresh()}function v(){a.galleryElement.innerHTML=""}function h(){a.loaderBackdrop.classList.remove("hidden")}function y(){a.loaderBackdrop.classList.add("hidden")}function p(){a.loadMoreBtn.classList.remove("hidden")}function d(){a.loadMoreBtn.classList.add("hidden")}let u="",c=1,f=0;a.formEl.addEventListener("submit",M);a.loadMoreBtn.addEventListener("click",P);async function M(t){t.preventDefault();const r=t.target.elements["search-text"].value.trim();if(!r){l.warning({message:"Please enter search text!",position:"topRight"});return}u=r,c=1,v(),d(),h();try{const n=await m(u,c);if(!n.hits.length){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}f=n.totalHits,g(n.hits),f>=n.hits.length&&p()}catch{l.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{y(),t.target.reset()}}async function P(){d(),c+=1,h();try{const t=await m(u,c);g(t.hits),R(),document.querySelectorAll(".gallery-item").length>=f?(d(),l.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):p()}catch{l.error({title:"Error",message:"Something went wrong. Try again later.",position:"topRight"})}finally{y()}}function R(){const t=document.querySelector(".gallery-item");if(!t)return;const r=t.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
