import{a as w,S as B,i as s}from"./assets/vendor-DvfmeZXB.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const q="https://pixabay.com/api/",v="53377193-0ff55e0243d64b70ef9ccd5fb";async function m(r,t){const n={key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await w.get(q,{params:n})).data}const c={galleryElement:document.querySelector(".gallery"),loaderBackdrop:document.querySelector(".loader-backdrop"),loadmoreBtn:document.querySelector(".load-more")};console.log(c.loadmoreBtn);const P=new B(".gallery a",{captionsData:"alt",captionDelay:250});function g(r){const t=r.map(({largeImageURL:n,webformatURL:i,tags:e,likes:o,views:a,comments:L,downloads:S})=>`
      <li class="gallery-item">
        <a href="${n}">
          <img src="${i}" alt="${e}">
        </a>
        <ul class="card-info">
          <li><b>Likes:</b> ${o}</li>
          <li><b>Views:</b> ${a}</li>
          <li><b>Comments:</b> ${L}</li>
          <li><b>Downloads:</b> ${S}</li>
        </ul>
      </li>
    `).join("");c.galleryElement.insertAdjacentHTML("beforeend",t),P.refresh()}function E(){c.galleryElement.innerHTML=""}function h(){c.loaderBackdrop.classList.remove(".hidden")}function p(){c.loaderBackdrop.classList.add(".hidden")}const y=document.querySelector(".form"),f=document.querySelector(".load-more");let d="",l=1,u=0;function M(){f.style.display="block"}function b(){f.style.display="none"}y.addEventListener("submit",R);f.addEventListener("click",$);function R(r){r.preventDefault();const t=r.target.elements["search-text"].value.trim();if(!t){s.warning({message:"Please enter search text!",position:"topRight"});return}d=t,l=1,E(),b(),h(),m(d,l).then(n=>{if(u=n.totalHits,!n.hits.length){s.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(n.hits),u>l*15&&M()}).catch(()=>{s.error({message:"Something went wrong. Please try again later.",position:"topRight"})}).finally(()=>{p(),y.reset()})}function $(){l+=1,h(),m(d,l).then(r=>{g(r.hits),document.querySelectorAll(".gallery-item").length>=u&&(b(),s.info({message:"You've reached the end of search results.",position:"topRight"})),x()}).catch(()=>{s.error({message:"Something went wrong. Try again later.",position:"topRight"})}).finally(()=>{p()})}function x(){const r=document.querySelector(".gallery-item");if(!r)return;const t=r.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}console.log("The end!");
//# sourceMappingURL=index.js.map
