import{a as L,S as w,i as l}from"./assets/vendor-DvfmeZXB.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const S="https://pixabay.com/api/",B="53377193-0ff55e0243d64b70ef9ccd5fb";async function u(t,r){const n={key:B,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r};return(await L.get(S,{params:n})).data}const a={formEl:document.querySelector(".form"),galleryElement:document.querySelector(".gallery"),loaderBackdrop:document.querySelector(".loader-backdrop"),loadMoreBtn:document.querySelector(".load-more")},E=new w(".gallery a",{captionsData:"alt",captionDelay:250});function f(t){const r=t.map(({largeImageURL:n,webformatURL:i,tags:e,likes:o,views:s,comments:p,downloads:b})=>`
      <li class="gallery-item">
        <a href="${n}">
          <img src="${i}" alt="${e}">
        </a>
        <ul class="card-info">
          <li><b>Likes:</b> ${o}</li>
          <li><b>Views:</b> ${s}</li>
          <li><b>Comments:</b> ${p}</li>
          <li><b>Downloads:</b> ${b}</li>
        </ul>
      </li>
    `).join("");a.galleryElement.insertAdjacentHTML("beforeend",r),E.refresh()}function q(){a.galleryElement.innerHTML=""}function m(){a.loaderBackdrop.classList.remove("hidden")}function g(){a.loaderBackdrop.classList.add("hidden")}function v(){a.loadMoreBtn.classList.remove("hidden")}function h(){a.loadMoreBtn.classList.add("hidden")}let d="",c=1,y=0;a.formEl.addEventListener("submit",M);a.loadMoreBtn.addEventListener("click",P);async function M(t){t.preventDefault();const r=t.target.elements["search-text"].value.trim();if(!r){l.warning({message:"Please enter search text!",position:"topRight"});return}d=r,c=1,q(),h(),m();try{const n=await u(d,c);if(!n.hits.length){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y=n.totalHits,f(n.hits),n.hits.length===15&&v()}catch{l.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{g(),t.target.reset()}}async function P(){c+=1,m();try{const t=await u(d,c);f(t.hits),R(),document.querySelectorAll(".gallery-item").length>=y&&(h(),l.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{l.error({title:"Error",message:"Something went wrong. Try again later.",position:"topRight"})}finally{g()}}function R(){const t=document.querySelector(".gallery-item");if(!t)return;const r=t.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
